---

- name: Create qtile.desktop file
  become: true
  template:
    src: templates/qtile.desktop
    dest: "/usr/share/xsessions/qtile.desktop"


- name: Enable dank material shell
  service:
    name: dsearch
    enabled: yes
